"""create studies

Revision ID: 709a0c5467bf
Revises: 
Create Date: 2026-01-28 12:47:57.856147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709a0c5467bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('protocol_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Active', name='study_status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studies_protocol_code'), 'studies', ['protocol_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_studies_protocol_code'), table_name='studies')
    op.drop_table('studies')
    # ### end Alembic commands ###
