"""shcedule visit table

Revision ID: 74c145ca1f5a
Revises: e54aab74e4d5
Create Date: 2026-01-30 10:25:31.675300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c145ca1f5a'
down_revision: Union[str, None] = 'e54aab74e4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_visits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('visit_template_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Done', name='scheduledvisitstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_template_id'], ['visit_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'visit_template_id', name='uq_subject_visit_template')
    )
    op.create_index(op.f('ix_scheduled_visits_subject_id'), 'scheduled_visits', ['subject_id'], unique=False)
    op.create_index(op.f('ix_scheduled_visits_visit_template_id'), 'scheduled_visits', ['visit_template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_visits_visit_template_id'), table_name='scheduled_visits')
    op.drop_index(op.f('ix_scheduled_visits_subject_id'), table_name='scheduled_visits')
    op.drop_table('scheduled_visits')
    # ### end Alembic commands ###
