"""create subjects

Revision ID: 77f9edc04f39
Revises: ea803ac48fdf
Create Date: 2026-01-30 09:01:29.411938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f9edc04f39'
down_revision: Union[str, None] = 'ea803ac48fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('subject_identifier', sa.String(length=64), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'subject_identifier', name='uq_subject_study_identifier')
    )
    op.create_index(op.f('ix_subjects_study_id'), 'subjects', ['study_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_study_id'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
