"""create form templates and fields

Revision ID: 9e1f3b8a678c
Revises: fb5fd384697b
Create Date: 2026-01-28 14:39:20.525157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1f3b8a678c'
down_revision: Union[str, None] = 'fb5fd384697b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'code', name='uq_form_template_study_code')
    )
    op.create_index(op.f('ix_form_templates_study_id'), 'form_templates', ['study_id'], unique=False)
    op.create_table('form_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_template_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('Text', 'Number', 'Date', name='field_type'), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_template_id'], ['form_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_template_id', 'key', name='uq_form_field_form_key')
    )
    op.create_index(op.f('ix_form_fields_form_template_id'), 'form_fields', ['form_template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_fields_form_template_id'), table_name='form_fields')
    op.drop_table('form_fields')
    op.drop_index(op.f('ix_form_templates_study_id'), table_name='form_templates')
    op.drop_table('form_templates')
    # ### end Alembic commands ###
