"""add form_entry and field_value tables

Revision ID: af66cc6866f1
Revises: 74c145ca1f5a
Create Date: 2026-01-30 15:33:35.053597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af66cc6866f1'
down_revision: Union[str, None] = '74c145ca1f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheduled_visit_id', sa.Integer(), nullable=False),
    sa.Column('form_template_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Draft', 'Submitted', name='formentrystatus', native_enum=False), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_template_id'], ['form_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduled_visit_id'], ['scheduled_visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheduled_visit_id', 'form_template_id', name='uq_form_entry_visit_form')
    )
    op.create_index(op.f('ix_form_entries_form_template_id'), 'form_entries', ['form_template_id'], unique=False)
    op.create_index(op.f('ix_form_entries_scheduled_visit_id'), 'form_entries', ['scheduled_visit_id'], unique=False)
    op.create_table('field_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('form_entry_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_entry_id'], ['form_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_entry_id', 'field_id', name='uq_field_value_entry_field')
    )
    op.create_index(op.f('ix_field_values_field_id'), 'field_values', ['field_id'], unique=False)
    op.create_index(op.f('ix_field_values_form_entry_id'), 'field_values', ['form_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_field_values_form_entry_id'), table_name='field_values')
    op.drop_index(op.f('ix_field_values_field_id'), table_name='field_values')
    op.drop_table('field_values')
    op.drop_index(op.f('ix_form_entries_scheduled_visit_id'), table_name='form_entries')
    op.drop_index(op.f('ix_form_entries_form_template_id'), table_name='form_entries')
    op.drop_table('form_entries')
    # ### end Alembic commands ###
