"""attach forms to visit templates

Revision ID: e521350f1a84
Revises: 9e1f3b8a678c
Create Date: 2026-01-28 14:52:00.267519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e521350f1a84'
down_revision: Union[str, None] = '9e1f3b8a678c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_template_forms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visit_template_id', sa.Integer(), nullable=False),
    sa.Column('form_template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_template_id'], ['form_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_template_id'], ['visit_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_template_id', 'form_template_id', name='uq_vt_form_unique')
    )
    op.create_index(op.f('ix_visit_template_forms_form_template_id'), 'visit_template_forms', ['form_template_id'], unique=False)
    op.create_index(op.f('ix_visit_template_forms_visit_template_id'), 'visit_template_forms', ['visit_template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_template_forms_visit_template_id'), table_name='visit_template_forms')
    op.drop_index(op.f('ix_visit_template_forms_form_template_id'), table_name='visit_template_forms')
    op.drop_table('visit_template_forms')
    # ### end Alembic commands ###
