"""shchedule_generated col added to subject

Revision ID: e54aab74e4d5
Revises: 77f9edc04f39
Create Date: 2026-01-30 10:05:09.027111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e54aab74e4d5'
down_revision: Union[str, None] = '77f9edc04f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('schedule_generated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'schedule_generated')
    # ### end Alembic commands ###
