"""studies table changed

Revision ID: ea803ac48fdf
Revises: e521350f1a84
Create Date: 2026-01-28 23:40:35.225757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea803ac48fdf'
down_revision: Union[str, None] = 'e521350f1a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('studies', 'status',
               existing_type=postgresql.ENUM('Draft', 'Active', name='study_status'),
               type_=sa.Enum('Draft', 'Active', name='studystatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('studies', 'status',
               existing_type=sa.Enum('Draft', 'Active', name='studystatus', native_enum=False),
               type_=postgresql.ENUM('Draft', 'Active', name='study_status'),
               existing_nullable=False)
    # ### end Alembic commands ###
