"""create visit_templates

Revision ID: fb5fd384697b
Revises: 709a0c5467bf
Create Date: 2026-01-28 13:44:55.626703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5fd384697b'
down_revision: Union[str, None] = '709a0c5467bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('window_before', sa.Integer(), nullable=False),
    sa.Column('window_after', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id', 'code', name='uq_visit_template_study_code')
    )
    op.create_index('ix_visit_templates_study_day', 'visit_templates', ['study_id', 'day'], unique=False)
    op.create_index(op.f('ix_visit_templates_study_id'), 'visit_templates', ['study_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_templates_study_id'), table_name='visit_templates')
    op.drop_index('ix_visit_templates_study_day', table_name='visit_templates')
    op.drop_table('visit_templates')
    # ### end Alembic commands ###
